name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group  # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clear cache
        run: rm -rf node_modules dist

      - name: Install dependencies
        run: npm ci
      
      - name: Install tsconfig-paths
        run: npm install tsconfig-paths --save-dev

      - name: Build project
        run: npm run build
      
      - name: Verify build output
        run: ls -R dist || echo "No build output found"

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
